apiVersion: v1
kind: Pod
metadata:
  name: chatpod
  labels:
    type: test
    role: title
spec:
  containers:          
    - name: database
      image: postgres:latest
      args:
        - 
      ports:
        - containerPort: 222
          hostPort: 33
    - name: blob
      image: bitnami/minio
      args:
        -
      ports:
        - containerPort: 222
          hostPort: 22
    - name: cache
      image: redis:latest
      args:
        -
      ports:
        - containerPort: 11
    - name: mainapp
      image:
      ports:
        - containerPort: 80
          hostPort: 80
  restartPolicy: Always
  